"""Immutable local artifact storage adapter.

The storage key is generated by the application and is treated as an opaque
relative key. Path traversal and symlink escapes are rejected before any I/O.
"""

from __future__ import annotations

import asyncio
from hashlib import sha256
from pathlib import Path
from uuid import uuid4

from andromeda_ingestion.domain.errors import StorageError


class FileSystemArtifactStorage:
    def __init__(self, root: str | Path) -> None:
        self.root = Path(root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    async def put(self, key: str, content: bytes) -> str:
        return await asyncio.to_thread(self._put, key, content)

    async def get(self, key: str, expected_checksum: str | None = None) -> bytes:
        return await asyncio.to_thread(self._get, key, expected_checksum)

    async def exists(self, key: str) -> bool:
        path = self._safe_path(key)
        return await asyncio.to_thread(path.is_file)

    def _put(self, key: str, content: bytes) -> str:
        path = self._safe_path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_name(f".{path.name}.{uuid4().hex}.tmp")
        try:
            temporary.write_bytes(content)
            temporary.replace(path)
        except OSError as exc:
            temporary.unlink(missing_ok=True)
            raise StorageError("ARTIFACT_WRITE_FAILED", "Could not persist raw artifact", {"key": key}) from exc
        return key

    def _get(self, key: str, expected_checksum: str | None = None) -> bytes:
        path = self._safe_path(key)
        try:
            content = path.read_bytes()
        except OSError as exc:
            raise StorageError("ARTIFACT_READ_FAILED", "Could not read raw artifact", {"key": key}) from exc
        if expected_checksum and self.checksum(content) != expected_checksum:
            raise StorageError("ARTIFACT_CHECKSUM_MISMATCH", "Stored artifact checksum does not match metadata", {"key": key})
        return content

    def _safe_path(self, key: str) -> Path:
        candidate = (self.root / key).resolve()
        try:
            candidate.relative_to(self.root)
        except ValueError as exc:
            raise StorageError("INVALID_STORAGE_KEY", "Artifact storage key escapes storage root", {"key": key}) from exc
        if not key or Path(key).is_absolute() or ".." in Path(key).parts:
            raise StorageError("INVALID_STORAGE_KEY", "Artifact storage key must be relative", {"key": key})
        return candidate

    @staticmethod
    def checksum(content: bytes) -> str:
        return sha256(content).hexdigest()
