"""Persistence ports; concrete SQLAlchemy adapters live outside the domain."""

from __future__ import annotations

from typing import Any, Protocol


class IngestionRepositoryPort(Protocol):
    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...

    async def get_source(self, source_id: str) -> dict[str, Any]: ...

    async def get_source_by_key(self, stable_key: str) -> dict[str, Any] | None: ...

    async def list_sources(self, enabled: bool | None = None) -> list[dict[str, Any]]: ...

    async def upsert_source(self, data: dict[str, Any]) -> dict[str, Any]: ...

    async def upsert_discovered_item(self, data: dict[str, Any]) -> dict[str, Any]: ...

    async def get_discovered_item(self, item_id: str) -> dict[str, Any]: ...

    async def list_discovered_items(self, source_id: str, limit: int = 200) -> list[dict[str, Any]]: ...

    async def get_artifact(self, artifact_id: str) -> dict[str, Any]: ...

    async def find_artifact(self, source_id: str, canonical_url: str, checksum: str) -> dict[str, Any] | None: ...

    async def get_current_artifact(self, source_id: str, canonical_url: str) -> dict[str, Any] | None: ...

    async def create_artifact(self, data: dict[str, Any]) -> dict[str, Any]: ...

    async def get_prepared(self, artifact_id: str) -> dict[str, Any] | None: ...

    async def upsert_prepared(self, data: dict[str, Any]) -> dict[str, Any]: ...

    async def get_profile(self, profile_id: str) -> dict[str, Any]: ...

    async def get_profile_by_code(self, profile_code: str, version: int | None = None) -> dict[str, Any] | None: ...

    async def upsert_profile(self, data: dict[str, Any]) -> dict[str, Any]: ...

    async def create_extraction(self, data: dict[str, Any]) -> dict[str, Any]: ...

    async def get_extraction(self, extraction_id: str) -> dict[str, Any]: ...

    async def update_extraction_status(self, extraction_id: str, status: str) -> dict[str, Any]: ...

    async def find_extraction(self, artifact_id: str, profile_id: str, input_fingerprint: str) -> dict[str, Any] | None: ...

    async def find_latest_extraction_for_artifact(self, artifact_id: str, profile_id: str) -> dict[str, Any] | None: ...

    async def list_candidates(self, extraction_id: str, status: str | None = None) -> list[dict[str, Any]]: ...

    async def create_candidate(self, data: dict[str, Any]) -> dict[str, Any]: ...

    async def update_candidate(self, candidate_id: str, data: dict[str, Any], expected_version: int | None = None) -> dict[str, Any]: ...

    async def get_candidate(self, candidate_id: str) -> dict[str, Any]: ...

    async def upsert_change(self, data: dict[str, Any]) -> dict[str, Any]: ...

    async def list_changes(self, kind: str | None = None, limit: int = 100) -> list[dict[str, Any]]: ...

    async def get_pipeline(self, pipeline_id: str) -> dict[str, Any]: ...

    async def get_pipeline_by_key(self, idempotency_key: str) -> dict[str, Any] | None: ...

    async def create_pipeline(self, data: dict[str, Any]) -> dict[str, Any]: ...

    async def update_pipeline(self, pipeline_id: str, data: dict[str, Any], expected_version: int | None = None) -> dict[str, Any]: ...

    async def create_job(self, data: dict[str, Any]) -> dict[str, Any]: ...

    async def get_job(self, job_id: str) -> dict[str, Any]: ...

    async def get_job_by_key(self, idempotency_key: str) -> dict[str, Any] | None: ...

    async def update_job(self, job_id: str, data: dict[str, Any], expected_version: int | None = None) -> dict[str, Any]: ...

    async def list_jobs(self, state: str | None = None, limit: int = 100) -> list[dict[str, Any]]: ...

    async def record_audit(self, data: dict[str, Any]) -> dict[str, Any]: ...

    async def database_ready(self) -> bool: ...


def as_payload(value: Any) -> dict[str, Any]:
    """Normalize a Pydantic/dataclass payload at an adapter seam."""

    if hasattr(value, "model_dump"):
        return value.model_dump(mode="json")
    if isinstance(value, dict):
        return value
    raise TypeError(f"unsupported repository payload: {type(value)!r}")
