"""create ingestion core

Revision ID: fe1e4ce1da7f
Revises: 
Create Date: 2026-09-24 21:02:05.478370
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'fe1e4ce1da7f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_table('extraction_profiles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('profile_code', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('expected_document_types_json', sa.JSON(), nullable=False),
    sa.Column('expected_ontology_concepts_json', sa.JSON(), nullable=False),
    sa.Column('output_schema_json', sa.JSON(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('validation_rules_json', sa.JSON(), nullable=False),
    sa.Column('ai_strategy', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_code', 'version', name='uq_profile_code_version')
    )
    op.create_index(op.f('ix_extraction_profiles_status'), 'extraction_profiles', ['status'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_jobs_correlation_id'), 'jobs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_jobs_next_retry_at'), 'jobs', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_table('source_definitions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('stable_key', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('source_category', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('discovery_strategy', sa.String(length=64), nullable=False),
    sa.Column('fetch_strategy', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('trust_level', sa.String(length=64), nullable=False),
    sa.Column('refresh_policy_json', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('allowed_hosts_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_definitions_enabled'), 'source_definitions', ['enabled'], unique=False)
    op.create_index(op.f('ix_source_definitions_source_category'), 'source_definitions', ['source_category'], unique=False)
    op.create_index(op.f('ix_source_definitions_stable_key'), 'source_definitions', ['stable_key'], unique=True)
    op.create_table('discovered_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('document_kind', sa.String(length=128), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discovery_method', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'canonical_url', name='uq_discovered_source_url')
    )
    op.create_index(op.f('ix_discovered_items_document_kind'), 'discovered_items', ['document_kind'], unique=False)
    op.create_index(op.f('ix_discovered_items_source_id'), 'discovered_items', ['source_id'], unique=False)
    op.create_index(op.f('ix_discovered_items_status'), 'discovered_items', ['status'], unique=False)
    op.create_table('raw_artifacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('discovered_item_id', sa.String(length=64), nullable=True),
    sa.Column('requested_url', sa.String(length=2048), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('final_url', sa.String(length=2048), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('etag', sa.String(length=512), nullable=True),
    sa.Column('last_modified', sa.String(length=512), nullable=True),
    sa.Column('raw_content_location', sa.String(length=2048), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('previous_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['discovered_item_id'], ['discovered_items.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'canonical_url', 'checksum', name='uq_artifact_source_url_checksum')
    )
    op.create_index('ix_artifact_source_current', 'raw_artifacts', ['source_id', 'canonical_url', 'is_current'], unique=False)
    op.create_index(op.f('ix_raw_artifacts_canonical_url'), 'raw_artifacts', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_raw_artifacts_is_current'), 'raw_artifacts', ['is_current'], unique=False)
    op.create_index(op.f('ix_raw_artifacts_retrieved_at'), 'raw_artifacts', ['retrieved_at'], unique=False)
    op.create_index(op.f('ix_raw_artifacts_source_id'), 'raw_artifacts', ['source_id'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('output_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('warnings_json', sa.JSON(), nullable=False),
    sa.Column('confidence_summary_json', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('token_usage_json', sa.JSON(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['raw_artifacts.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['extraction_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'profile_id', 'input_fingerprint', name='uq_extraction_input')
    )
    op.create_index(op.f('ix_extractions_artifact_id'), 'extractions', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_extractions_profile_id'), 'extractions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_extractions_status'), 'extractions', ['status'], unique=False)
    op.create_table('prepared_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('preparation_version', sa.String(length=64), nullable=False),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('sections_json', sa.JSON(), nullable=False),
    sa.Column('tables_json', sa.JSON(), nullable=False),
    sa.Column('links_json', sa.JSON(), nullable=False),
    sa.Column('chunks_json', sa.JSON(), nullable=False),
    sa.Column('structural_hints_json', sa.JSON(), nullable=False),
    sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['raw_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prepared_documents_artifact_id'), 'prepared_documents', ['artifact_id'], unique=True)
    op.create_index(op.f('ix_prepared_documents_content_fingerprint'), 'prepared_documents', ['content_fingerprint'], unique=False)
    op.create_table('change_candidates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('extraction_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('target_key', sa.String(length=512), nullable=False),
    sa.Column('before_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('after_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('before_payload_json', sa.JSON(), nullable=True),
    sa.Column('after_payload_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reason', sa.String(length=2000), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['raw_artifacts.id'], ),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_index(op.f('ix_change_candidates_artifact_id'), 'change_candidates', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_change_candidates_extraction_id'), 'change_candidates', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_change_candidates_kind'), 'change_candidates', ['kind'], unique=False)
    op.create_index(op.f('ix_change_candidates_status'), 'change_candidates', ['status'], unique=False)
    op.create_index(op.f('ix_change_candidates_target_key'), 'change_candidates', ['target_key'], unique=False)
    op.create_table('extraction_candidates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('extraction_id', sa.String(length=64), nullable=False),
    sa.Column('candidate_kind', sa.String(length=64), nullable=False),
    sa.Column('natural_key', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence_status', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('validation_json', sa.JSON(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('core_source_id', sa.String(length=64), nullable=True),
    sa.Column('core_observation_id', sa.String(length=64), nullable=True),
    sa.Column('review_id', sa.String(length=64), nullable=True),
    sa.Column('proposal_id', sa.String(length=64), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extraction_id', 'natural_key', name='uq_candidate_extraction_key')
    )
    op.create_index(op.f('ix_extraction_candidates_candidate_kind'), 'extraction_candidates', ['candidate_kind'], unique=False)
    op.create_index(op.f('ix_extraction_candidates_extraction_id'), 'extraction_candidates', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_extraction_candidates_status'), 'extraction_candidates', ['status'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('discovered_item_id', sa.String(length=64), nullable=True),
    sa.Column('artifact_id', sa.String(length=64), nullable=True),
    sa.Column('extraction_id', sa.String(length=64), nullable=True),
    sa.Column('profile_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('transition_history_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['raw_artifacts.id'], ),
    sa.ForeignKeyConstraint(['discovered_item_id'], ['discovered_items.id'], ),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['extraction_profiles.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_pipeline_runs_correlation_id'), 'pipeline_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_source_id'), 'pipeline_runs', ['source_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_state'), 'pipeline_runs', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_runs_state'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_source_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_correlation_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_extraction_candidates_status'), table_name='extraction_candidates')
    op.drop_index(op.f('ix_extraction_candidates_extraction_id'), table_name='extraction_candidates')
    op.drop_index(op.f('ix_extraction_candidates_candidate_kind'), table_name='extraction_candidates')
    op.drop_table('extraction_candidates')
    op.drop_index(op.f('ix_change_candidates_target_key'), table_name='change_candidates')
    op.drop_index(op.f('ix_change_candidates_status'), table_name='change_candidates')
    op.drop_index(op.f('ix_change_candidates_kind'), table_name='change_candidates')
    op.drop_index(op.f('ix_change_candidates_extraction_id'), table_name='change_candidates')
    op.drop_index(op.f('ix_change_candidates_artifact_id'), table_name='change_candidates')
    op.drop_table('change_candidates')
    op.drop_index(op.f('ix_prepared_documents_content_fingerprint'), table_name='prepared_documents')
    op.drop_index(op.f('ix_prepared_documents_artifact_id'), table_name='prepared_documents')
    op.drop_table('prepared_documents')
    op.drop_index(op.f('ix_extractions_status'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_profile_id'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_artifact_id'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_raw_artifacts_source_id'), table_name='raw_artifacts')
    op.drop_index(op.f('ix_raw_artifacts_retrieved_at'), table_name='raw_artifacts')
    op.drop_index(op.f('ix_raw_artifacts_is_current'), table_name='raw_artifacts')
    op.drop_index(op.f('ix_raw_artifacts_canonical_url'), table_name='raw_artifacts')
    op.drop_index('ix_artifact_source_current', table_name='raw_artifacts')
    op.drop_table('raw_artifacts')
    op.drop_index(op.f('ix_discovered_items_status'), table_name='discovered_items')
    op.drop_index(op.f('ix_discovered_items_source_id'), table_name='discovered_items')
    op.drop_index(op.f('ix_discovered_items_document_kind'), table_name='discovered_items')
    op.drop_table('discovered_items')
    op.drop_index(op.f('ix_source_definitions_stable_key'), table_name='source_definitions')
    op.drop_index(op.f('ix_source_definitions_source_category'), table_name='source_definitions')
    op.drop_index(op.f('ix_source_definitions_enabled'), table_name='source_definitions')
    op.drop_table('source_definitions')
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_next_retry_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_correlation_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_extraction_profiles_status'), table_name='extraction_profiles')
    op.drop_table('extraction_profiles')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
