"""Shared value objects and enums used by the domain contracts."""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum


def utc_now() -> datetime:
    return datetime.now(UTC)


class SourceCategory(StrEnum):
    UNIVERSITY = "UNIVERSITY"
    MINISTRY = "MINISTRY"
    GOVERNMENT = "GOVERNMENT"
    OLYMPIAD_ORGANIZER = "OLYMPIAD_ORGANIZER"
    REGULATOR = "REGULATOR"
    OTHER_OFFICIAL_SOURCE = "OTHER_OFFICIAL_SOURCE"


class SourceType(StrEnum):
    WEB_PAGE = "WEB_PAGE"
    PDF = "PDF"
    API = "API"
    DOCUMENT = "DOCUMENT"
    MANUAL = "MANUAL"
    IMPORT = "IMPORT"


class DiscoveryStrategy(StrEnum):
    STATIC_URL = "STATIC_URL"
    SITEMAP = "SITEMAP"
    HTML_LINK_DISCOVERY = "HTML_LINK_DISCOVERY"
    API_DISCOVERY = "API_DISCOVERY"
    SEARCH = "SEARCH"
    FEED = "FEED"
    AI_ASSISTED_DISCOVERY = "AI_ASSISTED_DISCOVERY"


class FetchStrategy(StrEnum):
    HTTP = "HTTP"
    BROWSER = "BROWSER"
    FILE = "FILE"
    API = "API"
    FIXTURE = "FIXTURE"


class TrustLevel(StrEnum):
    OFFICIAL_PRIMARY = "OFFICIAL_PRIMARY"
    OFFICIAL_SECONDARY = "OFFICIAL_SECONDARY"
    TRUSTED_AGGREGATOR = "TRUSTED_AGGREGATOR"
    UNVERIFIED = "UNVERIFIED"


class ConfidenceStatus(StrEnum):
    VERIFIED = "VERIFIED"
    HIGH_CONFIDENCE = "HIGH_CONFIDENCE"
    UNCERTAIN = "UNCERTAIN"
    CONFLICTING = "CONFLICTING"
    UNKNOWN = "UNKNOWN"


class CandidateStatus(StrEnum):
    EXTRACTED = "EXTRACTED"
    VALIDATED = "VALIDATED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    REJECTED = "REJECTED"
    PUBLISHED = "PUBLISHED"
    PUBLISH_FAILED = "PUBLISH_FAILED"


class PipelineState(StrEnum):
    DISCOVERED = "DISCOVERED"
    FETCHING = "FETCHING"
    FETCHED = "FETCHED"
    PREPARING = "PREPARING"
    PREPARED = "PREPARED"
    EXTRACTING = "EXTRACTING"
    EXTRACTED = "EXTRACTED"
    VALIDATING = "VALIDATING"
    VALIDATED = "VALIDATED"
    PUBLISHING = "PUBLISHING"
    PUBLISHED = "PUBLISHED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    FAILED = "FAILED"
    RETRYABLE = "RETRYABLE"
    SKIPPED_UNCHANGED = "SKIPPED_UNCHANGED"


class JobState(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    RETRYABLE = "RETRYABLE"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    NEEDS_REVIEW = "NEEDS_REVIEW"


class ChangeKind(StrEnum):
    ADDED = "ADDED"
    MODIFIED = "MODIFIED"
    REMOVED = "REMOVED"
    POSSIBLY_REPLACED = "POSSIBLY_REPLACED"
    AMBIGUOUS = "AMBIGUOUS"


class FailureCode(StrEnum):
    DISCOVERY_FAILED = "DISCOVERY_FAILED"
    FETCH_FAILED = "FETCH_FAILED"
    FETCH_TIMEOUT = "FETCH_TIMEOUT"
    FETCH_RATE_LIMIT = "FETCH_RATE_LIMIT"
    FETCH_SSRF_REJECTED = "FETCH_SSRF_REJECTED"
    FETCH_BODY_TOO_LARGE = "FETCH_BODY_TOO_LARGE"
    PREPARATION_FAILED = "PREPARATION_FAILED"
    AI_TIMEOUT = "AI_TIMEOUT"
    AI_RATE_LIMIT = "AI_RATE_LIMIT"
    AI_INVALID_OUTPUT = "AI_INVALID_OUTPUT"
    AI_PROVIDER_UNAVAILABLE = "AI_PROVIDER_UNAVAILABLE"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    CORE_UNAVAILABLE = "CORE_UNAVAILABLE"
    CORE_VALIDATION_FAILED = "CORE_VALIDATION_FAILED"
    AMBIGUOUS_EXTRACTION = "AMBIGUOUS_EXTRACTION"
    UNKNOWN_CONCEPT = "UNKNOWN_CONCEPT"
    CONCURRENT_UPDATE = "CONCURRENT_UPDATE"


def validate_interval(valid_from: datetime | None, valid_to: datetime | None) -> None:
    if valid_from is not None and valid_to is not None and valid_to <= valid_from:
        raise ValueError("valid_to must be after valid_from")
